# Generated by Django 6.1 on 2026-09-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MontseguroLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('mes_referencia', models.CharField(max_length=7)),
                ('canal', models.CharField(max_length=50)),
                ('porte_empresa', models.CharField(max_length=30)),
                ('vidas_estimadas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prop5Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('mes_referencia', models.CharField(max_length=7)),
                ('canal', models.CharField(max_length=50)),
                ('pais_residencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechbraboLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('mes_referencia', models.CharField(max_length=7)),
                ('canal', models.CharField(max_length=50)),
                ('tipo_solucao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('montseguro', 'Montseguro'), ('prop5', 'Prop5'), ('techbrabo', 'TechBrabo')], max_length=20)),
                ('mes', models.CharField(max_length=7)),
                ('canal', models.CharField(max_length=50)),
                ('investimento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leads_gerados', models.PositiveIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'mes'], name='api_marketi_empresa_b43602_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('montseguro', 'Montseguro'), ('prop5', 'Prop5'), ('techbrabo', 'TechBrabo')], max_length=20)),
                ('mes', models.CharField(max_length=7)),
                ('meta_receita', models.DecimalField(decimal_places=2, max_digits=14)),
                ('meta_quantidade', models.PositiveIntegerField(help_text='novos contratos/fechamentos esperados no mês')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'mes'], name='api_metaemp_empresa_a1e4ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='MontseguroFunil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=100)),
                ('operadora', models.CharField(blank=True, max_length=50, null=True)),
                ('vidas', models.PositiveIntegerField()),
                ('premio_mensal_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_cotacao', models.DateField(blank=True, null=True)),
                ('data_proposta', models.DateField(blank=True, null=True)),
                ('data_contratacao', models.DateField(blank=True, null=True)),
                ('data_implantacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=40)),
                ('motivo_perda', models.CharField(blank=True, max_length=100, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funil', to='api.montsegurolead')),
            ],
        ),
        migrations.CreateModel(
            name='MontseguroClienteAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(max_length=50)),
                ('vidas_ativas', models.PositiveIntegerField()),
                ('premio_mensal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_ativacao', models.DateField()),
                ('cancelado', models.BooleanField(default=False)),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_ativo', to='api.montsegurolead')),
            ],
        ),
        migrations.CreateModel(
            name='Prop5Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=100)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('probabilidade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estagio', models.CharField(max_length=50)),
                ('data_diagnostico', models.DateField(blank=True, null=True)),
                ('data_reuniao_consultiva', models.DateField(blank=True, null=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('valor_fechado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidade', to='api.prop5lead')),
            ],
        ),
        migrations.CreateModel(
            name='TechbraboOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=100)),
                ('tipo_solucao', models.CharField(max_length=50)),
                ('tipo_receita', models.CharField(max_length=20)),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estagio', models.CharField(max_length=50)),
                ('cliente_existente', models.BooleanField(default=False)),
                ('data_proposta', models.DateField(blank=True, null=True)),
                ('data_contrato', models.DateField(blank=True, null=True)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidade', to='api.techbrabolead')),
            ],
        ),
        migrations.CreateModel(
            name='TechbraboProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solucao', models.CharField(max_length=50)),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=14)),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=14)),
                ('margem_percentual', models.DecimalField(decimal_places=1, max_digits=5)),
                ('status', models.CharField(max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_entrega_prevista', models.DateField()),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oportunidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='api.techbrabooportunidade')),
            ],
        ),
    ]
