# Generated by Django 6.1 on 2026-08-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('investimento_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ticket_medio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ciclo_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=50)),
                ('empresa_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('estagio', models.CharField(max_length=50)),
                ('probabilidade', models.FloatField(default=0.0)),
                ('data_previsao_fechamento', models.DateField(blank=True, null=True)),
                ('valor_potencial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('receita_reconhecida', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('custo_investimento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Ganha', 'Ganha'), ('Perdida', 'Perdida')], default='Aberta', max_length=20)),
                ('vidas_contratadas', models.IntegerField(blank=True, null=True)),
                ('pais_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_receita', models.CharField(blank=True, max_length=20, null=True)),
                ('mrr_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campanha')),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.canal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=7)),
                ('investimento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.canal')),
            ],
            options={
                'unique_together': {('ano_mes', 'canal')},
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=7)),
                ('meta_receita', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
            options={
                'unique_together': {('ano_mes', 'empresa')},
            },
        ),
    ]
